Kuteba/Controllers/AddEmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogic;
using Database;
using ViewModels;

namespace Kuteba.Controllers
{
    public class AddEmployeeController : Controller
    {
        KutebaDatabase db;
        EmployeeManager em;

        public AddEmployeeController()
        {
             db = new KutebaDatabase();
             em = new EmployeeManager(db);
        }

        // GET: Add
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult Search(String ID)
        {
            var VM = em.ViewEmployee(ID);
            return Json(VM);
        }

        [HttpPost]
        public ActionResult Index(EmployeeViewmodel evm)
        {

            //gets all the Files uploaded to the viewmodel and compiles them into a File collection
           HttpFileCollection HFC =  System.Web.HttpContext.Current.Request.Files;

            //converts The Releative Path into an Absolute path on The Server hosting The website
            string path = System.Web.Hosting.HostingEnvironment.MapPath("/Contents/Upload");

            //for each of the files uploaded to The viewmodel, loop assigns A random name, add's it to the path and Generates a location
             foreach (HttpPostedFile v in HFC)
            {
                Guid newName = Guid.NewGuid();//Guid Type generates Random Name "newName"
                string FileLocation = System.IO.Path.Combine(path, newName.ToString());//combines Random name and path into a completed location
                
                v.SaveAs(FileLocation);
                System.IO.FileInfo ff = new System.IO.FileInfo(FileLocation);
            }
            em.AddEmployee(evm);
            return View();
        }
    }
}

Kuteba/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kuteba.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: EmployeeId
      
        public ActionResult EmployeeId()
        {
            return View();
        }
    }
}

Kuteba/Controllers/FinanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kuteba.Controllers
{
    
    [Authorize]
    public class FinanceController : Controller
    {
        // GET: Finance
        public ActionResult Index()
        {
            return View();
        }
    }
}

Kuteba/Controllers/SetSalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kuteba.Controllers
{
    public class SetSalaryController : Controller
    {
        // GET: SetSalary
        public ActionResult Index()
        {
            return View();
        }
    }
}

Kuteba/Views/Shared/_Layout.cshtml
﻿@{
    Layout = "/views/shared/_masterLayout.cshtml";
}



 @*<link type="text/css" rel="stylesheet" href="~/Contents/css/Signup.css" />*@



@section Styles{
<link type="text/css" rel="stylesheet" href="~/Contents/css/intialMenu.css" />
  @RenderSection("initalCSS",false)
 }


<div class="container1">

    <nav class="navi">
        <ul>
            <li><a href="~/About Us/index">ለበለጠ መረጃ</a></li>
            <li><a href="~/Announcement/index">ማስታወቂያ</a></li>
           <li><a href="~/login/signup">ይመዝገቡ</a></li> 
            <li><a href="~/login/index">ዋና-ገጸ</a></li>
        </ul>
</nav>
</div>     
 <div>
    @RenderSection("BodyPart", false)

</div>




Kuteba/Views/Shared/_LogedInAdminLayout.cshtml
@{
    Layout = "~/views/shared/_masterLayout.cshtml";
}

@section Styles{
    <link type="text/css" rel="stylesheet" href="~/Contents/css/adminlayout.css" />
    @RenderSection("initalCSS", false)
}
<section id="signout">
    <a href="@Url.Action("signout", "login")">
        እንካን ደህና መጡ @HttpContext.Current.User.Identity.Name     መዉጫ
    </a>
</section>



<div class="container">
    <nav class="navi">
        <div id="menu">
            <ul>
                <li>
                    <a href="#">@Resources.Resource.EmployeeList</a><span class="Darrow">&#9660;</span>
                    <ul class="sub1">
                        <li><a href="@Url.Action("EmployeeId", "Employee")">የቅጥረኛ መታወቅያ ቁጥር</a></li>
                        <li><a href="@Url.Action("Index", "SetSalary")">የቅጥረኛ ደሞዝ </a></li>
                    </ul>
                </li>
                <li>
                    <a href="#">የተገልጋይ ማውጫ</a><span class="Darrow">&#9660;</span> 
                    <ul class="sub1">
                        <li><a href="@Url.Action("ListUsers", "ListOfUsers")">የተገልጋይ ዝርዝር</a></li>
                        <li><a href="@Url.Action("Index", "Finance")">የሂሣብ ክፍል</a></li>
                       
                    </ul>
                </li>
                <li>
                    <a href="#">Employee Admin</a><span class="Darrow">&#9660;</span>
                    <ul class="sub1">
                        <li><a href="@Url.Action("index", "AddEmployee")">Add</a></li>
                        <li><a href="#">HOME</a></li>
                       
                    </ul>
                </li>
                <li>
                    <a href="#">የአስተዳደር ማስታወቂያ</a><span class="Darrow">&#9660;</span> @*Admin announcement*@
                    <ul class="sub1">

                        <li><a href="@Url.Action("Edit", "AnnouncementAdmin")">ማስተካከያ</a></li> @*Edit*@
                        <li><a href="@Url.Action("List", "AnnouncementAdmin")">ዝርዝር ማውጫ</a></li> @*list*@
                     
                    </ul>
                </li>

            </ul>
        </div>
    </nav>

</div>

@RenderSection("BodyPart", false)

Kuteba/Views/Shared/_LogedInUserLayout.cshtml
@{
    Layout = "~/views/shared/_masterLayout.cshtml";
}

@section Styles{
<link type="text/css" rel="stylesheet" href="~/Contents/css/adminlayout.css" />
   @RenderSection("initalCSS", false)
    }

  <div id="signout">
       
            እንካን ደህና መጡ @HttpContext.Current.User.Identity.Name  
            <a class="anchS-out"href="@Url.Action("signout", "login")"> መዉጫ</a> 
     
  </div>
  


    @*<div class="container">
        <nav class="navi">
            <div id="menu">
                <ul>
                    <li><a href="#">Home</a><span class="Darrow">&#9660;</span>
                        <ul class="sub1">
                            <li><a href="#">HOME</a></li>
                            <li><a href="#">HOME</a></li>
                        </ul>
                    </li>
                    <li><a href="#">User List</a><span class="Darrow">&#9660;</span>
                        <ul class="sub1">
                            <li><a href="@Url.Action("ListUsers", "ListOfUsers")">List Users</a></li>
                            <li><a href="#">HOME</a></li>
                            <li><a href="#">HOME</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Employee Admin</a><span class="Darrow">&#9660;</span>
                        <ul class="sub1">
                            <li><a href="@Url.Action("index", "AddEmployee")">Add</a></li>
                            <li><a href="@Url.Action("Index", "EmployeesList")">List</a></li>
                            <li><a href="#">HOME</a></li>
                        </ul>
                    </li>
                    <li><a href="#">Announcement Admin</a><span class="Darrow">&#9660;</span>
                        <ul class="sub1">

                            <li><a href="#">HOME</a></li>
                            <li><a href="#">HOME</a></li>
                            <li><a href="#">HOME</a></li>
                        </ul>
                    </li>

                </ul>
            </div>
        </nav>
        
    </div>*@

<div class="container">
        <nav class="navi">
            <div id="menu">
                <ul>
                    <li>
                        <a href="#">የቅጥረኛ መዝገብ</a><span class="Darrow">&#9660;</span>
                        <ul class="sub1">
                            <li><a href="@Url.Action("EmployeeId", "Employee")">የቅጥረኛ መታወቅያ ቁጥር</a></li>
                            <li><a href="@Url.Action("Index", "SetSalary")">የቅጥረኛ ደሞዝ </a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">የተገልጋይ ማውጫ</a><span class="Darrow">&#9660;</span>
                        <ul class="sub1">
                            <li><a href="@Url.Action("ListUsers", "ListOfUsers")">የተገልጋይ ዝርዝር</a></li>
                            <li><a href="@Url.Action("Index", "Finance")">የሂሣብ ክፍል</a></li>

                        </ul>
                    </li>
                    <li>
                        <a href="#">Employee Admin</a><span class="Darrow">&#9660;</span>
                        <ul class="sub1">
                            <li><a href="@Url.Action("index", "AddEmployee")">Add</a></li>
                             <li><a href="@Url.Action("Index", "EmployeesList")">List</a></li>

                        </ul>
                    </li>
                    <li>
                        <a href="#">የአስተዳደር ማስታወቂያ</a><span class="Darrow">&#9660;</span>
                        <ul class="sub1">

                            <li><a href="@Url.Action("Edit", "AnnouncementAdmin")">ማስተካከያ</a></li>
                            <li><a href="@Url.Action("List", "AnnouncementAdmin")">ዝርዝር ማውጫ</a></li>

                        </ul>
                    </li>

                </ul>
            </div>
        </nav>

    </div>

@RenderSection("BodyPart",false)

Kuteba/Views/Shared/_masterLayout.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_masterLayout</title>
    @*<link type="text/css" rel="stylesheet" href="~/Contents/css/login.css" />*@
    @*<link type="text/css" rel="stylesheet" href="~/Contents/css/Signup.css" />*@
    @*<link type="text/css" rel="stylesheet" href="~/Contents/css/announcement.css" />*@

    <link type="text/css" rel="stylesheet" href="~/Contents/css/site.css" />
    @RenderSection("Styles",false)
</head>
<body>
    <header>
        <div class="front">
            ቁጠባ<br /><p> የሂሳብ አያያዝ መፍትሄ</p>
        </div>
    </header>

    @RenderBody()


    <footer id="footer">
        <h2> ኮፒ-ራይት © ቁጠባ 2018 </h2>
    </footer>

</body>
</html>