Kuteba/Controllers/AnnouncementAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Database;
using BusinessLogic;
using ViewModels;
using Domain;

namespace Kuteba.Controllers
{
    public class AnnouncementAdminController : Controller
    {
        IAnnouncementService iaes;
        public AnnouncementAdminController()
        {
            KutebaDatabase kdb = new KutebaDatabase();
            iaes = new AnnouncementService(kdb);
        }
        // GET: AnnouncementAdmin
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult List()
        {

            return View();
        }
        [HttpGet]
        public ActionResult Edit()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Edit(AnnouncementViewModel avm)
        {
            if (ModelState.IsValid)
            {
                Announcemnets ans = iaes.EditNewAnnouncement(avm);
                return Redirect(Url.Action("Edit", "Index"));
            }
            else
            {
                ModelState.AddModelError("", "Incomplete form. Please try again.");
                return View();
            }
        }

    }
}

Kuteba/Views/AnnouncementAdmin/Edit.cshtml

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LogedInUserLayout.cshtml";
}

@section initalCSS{
<link type="text/css" rel="stylesheet" href="~/Contents/css/AdminForm.css" />
}

@section BodyPart{

    <div id="container2">
        <h2>  Edit form</h2>
        <form action="@Url.Action("Edit", "AnnouncementAdmin")" method="post">
            <fieldset class="Edit">
                <div class="fieldbox">
                    <label for="title">Title:</label>
                    <input id="name" Name="Title" type="text"
                           placeholder="Title" required>
                </div> <br />

                <div class="fieldbox">
                    <label for="picture">Picture:</label>
                    <input name="Picture" type="file"
                           placeholder="picture" required>
                </div> <br />


                <div class="fieldbox">
                    <label for="picture">Visible Date:</label>
                    <input id="dob" name="VisibleDate" type="date"
                           placeholder="Visible Date" required>
                </div> <br />


                <div class="fieldbox">
                    <label for="picture">Expire Date:</label>
                    <input id="dob" name="ExpireDate" type="date"
                           placeholder="Expire Date" required>
                </div> <br />

                <div class="fieldbox">

                    <label for="ContentDescription">Description:</label>
                    <input id="Description" name="ContentDescription" type="text"
                           placeholder="Details for describing" required>
                </div> <br />


                <input class="btn" type="submit"  id="edit" value="Edit"/>


            </fieldset>

        </form>

       
    </div>


 }


Kuteba/Views/AnnouncementAdmin/List.cshtml
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_LogedInUserLayout.cshtml";
}


@section initalCSS{
    <link type="text/css" rel="stylesheet" href="~/Contents/css/AdminForm.css" />
}

@section BodyPart{
    <div id="container2">

            <table border="1">
                <tr>
                    <th>Number</th>
                    <th>Name List</th>
                    <th>Amount of save</th>
                    <th class="edit">Edit</th>
                </tr>

                <tr>

                    <td>1</td>
                    <td>Elias kibret</td>
                    <td>100 birr</td>
                    <td class="edit">
                        <button>Edit</button>
                        <button>Delete</button>
                    </td>
                </tr>

                <tr>

                    <td>2</td>
                    <td>Donayam Nega</td>
                    <td>500 birr</td>
                    <td class="edit">
                        <button>Edit</button>
                        <button>Delete</button>
                    </td>
                </tr>
                <tr>

                    <td>3</td>
                    <td>Mahlet </td>
                    <td>200 birr</td>
                    <td class="edit">
                        <button>Edit</button>
                        <button>Delete</button>
                    </td>
                </tr>


            </table>
        </div>
       }